version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: feedrank-backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - VK_APP_ID=${VK_APP_ID}
      - VK_APP_SECRET=${VK_APP_SECRET}
      - VK_ACCESS_TOKEN=${VK_ACCESS_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - ./.env
    networks:
      - feedrank-network

  # Frontend service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: feedrank-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - feedrank-network

networks:
  feedrank-network:
    driver: bridge 