version: '3.9'

services:
  frontend:
    build: ./client
    container_name: feedrank-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file: .env

  backend:
    build: ./server
    container_name: feedrank-backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
    env_file: .env
    # depends_on:
    #   - mongo
  
  # mongo:
  #   image: mongo:5.0
  #   container_name: feedrank-mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   restart: unless-stopped
  #   env_file: .env

# volumes:
#   mongodb_data: