version: '3.9'

services:
  frontend:
    build: ./client
    container_name: feedrank-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build: ./server
    container_name: feedrank-backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/feedrank
      - JWT_SECRET=${JWT_SECRET}
      - VK_APP_ID=${VK_APP_ID}
      - VK_APP_SECRET=${VK_APP_SECRET}
      - VK_ACCESS_TOKEN=${VK_ACCESS_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - mongo
  
  mongo:
    image: mongo:5.0
    container_name: feedrank-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: